POST http://localhost:3001/user/login
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "password": "123456"
}

###
POST http://localhost:3001/user/register
Content-Type: application/json

{
  "email": "neumann@gmail.com",
  "password": "xxxxx",
  "name": "John von Neumann",
  "earlyAccessCode": "9b18e3152fe15eaba2310ddf574d8d04"
}

###
POST http://localhost:3001/user/refresh

###
get http://localhost:3001/db/projectCount

